#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ClCaLz.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Gly5GC.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Gly5PL.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Gly5State.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Gly6S.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//IClamp5.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Iar.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Ih_std.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//KNa.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//K_conc.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Ksyn.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//NMDA.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//NMDA_Kampa.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Na_conc.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Stim.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//Vclmp.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ampa.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ampa_m.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ampa_rt.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ampa_s.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ampa_trussell.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//bkpkj.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//cadecay.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//cadiff.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//cadyn.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//cap.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//cleftXmtr.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//coh.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//coh2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//coh3.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//coh4.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//exp3syn.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//gabaa.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//gabab.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//gluStim.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//gly.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//gly2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//gstim.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//hasenstaub.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//hcno.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//hh2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//iStim.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ican.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ihpkj.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ihsgc.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ihvcn.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//inav11.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//it.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//it2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//jsrnaf.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ka.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kht.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kht2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kir.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kleak.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//klt.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//klt2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kpkj.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kpkj2.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kpkjslow.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//kpksk.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//leak.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//lva.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//mcna.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//na.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//nadiff.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//nak_pump.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//pkjlk.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//pyr.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//ramp.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//rsg.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//spikerate.mod");
    fprintf(stderr," ../../PyNeuronLibrary/mechanisms//synstim.mod");
    fprintf(stderr, "\n");
  }
  _ClCaLz_reg();
  _Gly5GC_reg();
  _Gly5PL_reg();
  _Gly5State_reg();
  _Gly6S_reg();
  _IClamp5_reg();
  _Iar_reg();
  _Ih_std_reg();
  _KNa_reg();
  _K_conc_reg();
  _Ksyn_reg();
  _NMDA_reg();
  _NMDA_Kampa_reg();
  _Na_conc_reg();
  _Stim_reg();
  _Vclmp_reg();
  _ampa_reg();
  _ampa_m_reg();
  _ampa_rt_reg();
  _ampa_s_reg();
  _ampa_trussell_reg();
  _bkpkj_reg();
  _cadecay_reg();
  _cadiff_reg();
  _cadyn_reg();
  _cap_reg();
  _cleftXmtr_reg();
  _coh_reg();
  _coh2_reg();
  _coh3_reg();
  _coh4_reg();
  _exp3syn_reg();
  _gabaa_reg();
  _gabab_reg();
  _gluStim_reg();
  _gly_reg();
  _gly2_reg();
  _gstim_reg();
  _hasenstaub_reg();
  _hcno_reg();
  _hh2_reg();
  _iStim_reg();
  _ican_reg();
  _ihpkj_reg();
  _ihsgc_reg();
  _ihvcn_reg();
  _inav11_reg();
  _it_reg();
  _it2_reg();
  _jsrnaf_reg();
  _ka_reg();
  _kht_reg();
  _kht2_reg();
  _kir_reg();
  _kleak_reg();
  _klt_reg();
  _klt2_reg();
  _kpkj_reg();
  _kpkj2_reg();
  _kpkjslow_reg();
  _kpksk_reg();
  _leak_reg();
  _lva_reg();
  _mcna_reg();
  _na_reg();
  _nadiff_reg();
  _nak_pump_reg();
  _pkjlk_reg();
  _pyr_reg();
  _ramp_reg();
  _rsg_reg();
  _spikerate_reg();
  _synstim_reg();
}
