#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/nrn/i386/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/pbmanis/Desktop/Python/nrnlibrary/nrnlibrary/i386/.libs/libnrnmech.so" "$@"
